// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/kafka/v1/kafka.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	v1 "github.com/golangmonster/workspace-booking-service/pkg/api/model/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = v1.BookingStatus(0)
)

// Validate checks the field values on WorkspaceBooking with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WorkspaceBooking) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkspaceBooking with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WorkspaceBookingMultiError, or nil if none found.
func (m *WorkspaceBooking) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkspaceBooking) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BookingId

	// no validation rules for Status

	// no validation rules for WorkspaceId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetStartAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkspaceBookingValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkspaceBookingValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkspaceBookingValidationError{
				field:  "StartAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkspaceBookingValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkspaceBookingValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkspaceBookingValidationError{
				field:  "EndAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WorkspaceBookingMultiError(errors)
	}

	return nil
}

// WorkspaceBookingMultiError is an error wrapping multiple validation errors
// returned by WorkspaceBooking.ValidateAll() if the designated constraints
// aren't met.
type WorkspaceBookingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkspaceBookingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkspaceBookingMultiError) AllErrors() []error { return m }

// WorkspaceBookingValidationError is the validation error returned by
// WorkspaceBooking.Validate if the designated constraints aren't met.
type WorkspaceBookingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkspaceBookingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkspaceBookingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkspaceBookingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkspaceBookingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkspaceBookingValidationError) ErrorName() string { return "WorkspaceBookingValidationError" }

// Error satisfies the builtin error interface
func (e WorkspaceBookingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkspaceBooking.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkspaceBookingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkspaceBookingValidationError{}
