// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/workspace/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LatLon with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LatLon) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LatLon with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LatLonMultiError, or nil if none found.
func (m *LatLon) ValidateAll() error {
	return m.validate(true)
}

func (m *LatLon) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Lat

	// no validation rules for Lon

	if len(errors) > 0 {
		return LatLonMultiError(errors)
	}

	return nil
}

// LatLonMultiError is an error wrapping multiple validation errors returned by
// LatLon.ValidateAll() if the designated constraints aren't met.
type LatLonMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LatLonMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LatLonMultiError) AllErrors() []error { return m }

// LatLonValidationError is the validation error returned by LatLon.Validate if
// the designated constraints aren't met.
type LatLonValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LatLonValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LatLonValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LatLonValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LatLonValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LatLonValidationError) ErrorName() string { return "LatLonValidationError" }

// Error satisfies the builtin error interface
func (e LatLonValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLatLon.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LatLonValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LatLonValidationError{}

// Validate checks the field values on GetWorkspaceByIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWorkspaceByIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWorkspaceByIdRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWorkspaceByIdRequestMultiError, or nil if none found.
func (m *GetWorkspaceByIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWorkspaceByIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetWorkspaceByIdRequestMultiError(errors)
	}

	return nil
}

// GetWorkspaceByIdRequestMultiError is an error wrapping multiple validation
// errors returned by GetWorkspaceByIdRequest.ValidateAll() if the designated
// constraints aren't met.
type GetWorkspaceByIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWorkspaceByIdRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWorkspaceByIdRequestMultiError) AllErrors() []error { return m }

// GetWorkspaceByIdRequestValidationError is the validation error returned by
// GetWorkspaceByIdRequest.Validate if the designated constraints aren't met.
type GetWorkspaceByIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWorkspaceByIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWorkspaceByIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWorkspaceByIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWorkspaceByIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWorkspaceByIdRequestValidationError) ErrorName() string {
	return "GetWorkspaceByIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetWorkspaceByIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWorkspaceByIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWorkspaceByIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWorkspaceByIdRequestValidationError{}

// Validate checks the field values on GetWorkspaceByIdResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWorkspaceByIdResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWorkspaceByIdResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWorkspaceByIdResponseMultiError, or nil if none found.
func (m *GetWorkspaceByIdResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWorkspaceByIdResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetWorkspace()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponseValidationError{
					field:  "Workspace",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponseValidationError{
					field:  "Workspace",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWorkspace()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetWorkspaceByIdResponseValidationError{
				field:  "Workspace",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetWorkspaceByIdResponseMultiError(errors)
	}

	return nil
}

// GetWorkspaceByIdResponseMultiError is an error wrapping multiple validation
// errors returned by GetWorkspaceByIdResponse.ValidateAll() if the designated
// constraints aren't met.
type GetWorkspaceByIdResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWorkspaceByIdResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWorkspaceByIdResponseMultiError) AllErrors() []error { return m }

// GetWorkspaceByIdResponseValidationError is the validation error returned by
// GetWorkspaceByIdResponse.Validate if the designated constraints aren't met.
type GetWorkspaceByIdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWorkspaceByIdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWorkspaceByIdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWorkspaceByIdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWorkspaceByIdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWorkspaceByIdResponseValidationError) ErrorName() string {
	return "GetWorkspaceByIdResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetWorkspaceByIdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWorkspaceByIdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWorkspaceByIdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWorkspaceByIdResponseValidationError{}

// Validate checks the field values on CreateWorkspaceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateWorkspaceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateWorkspaceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateWorkspaceRequestMultiError, or nil if none found.
func (m *CreateWorkspaceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateWorkspaceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetCoordinates()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateWorkspaceRequestValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateWorkspaceRequestValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCoordinates()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateWorkspaceRequestValidationError{
				field:  "Coordinates",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for FullAddress

	// no validation rules for Type

	// no validation rules for Capacity

	if len(errors) > 0 {
		return CreateWorkspaceRequestMultiError(errors)
	}

	return nil
}

// CreateWorkspaceRequestMultiError is an error wrapping multiple validation
// errors returned by CreateWorkspaceRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateWorkspaceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateWorkspaceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateWorkspaceRequestMultiError) AllErrors() []error { return m }

// CreateWorkspaceRequestValidationError is the validation error returned by
// CreateWorkspaceRequest.Validate if the designated constraints aren't met.
type CreateWorkspaceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateWorkspaceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateWorkspaceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateWorkspaceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateWorkspaceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateWorkspaceRequestValidationError) ErrorName() string {
	return "CreateWorkspaceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateWorkspaceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateWorkspaceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateWorkspaceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateWorkspaceRequestValidationError{}

// Validate checks the field values on CreateWorkspaceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateWorkspaceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateWorkspaceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateWorkspaceResponseMultiError, or nil if none found.
func (m *CreateWorkspaceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateWorkspaceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkspaceId

	if len(errors) > 0 {
		return CreateWorkspaceResponseMultiError(errors)
	}

	return nil
}

// CreateWorkspaceResponseMultiError is an error wrapping multiple validation
// errors returned by CreateWorkspaceResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateWorkspaceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateWorkspaceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateWorkspaceResponseMultiError) AllErrors() []error { return m }

// CreateWorkspaceResponseValidationError is the validation error returned by
// CreateWorkspaceResponse.Validate if the designated constraints aren't met.
type CreateWorkspaceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateWorkspaceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateWorkspaceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateWorkspaceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateWorkspaceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateWorkspaceResponseValidationError) ErrorName() string {
	return "CreateWorkspaceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateWorkspaceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateWorkspaceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateWorkspaceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateWorkspaceResponseValidationError{}

// Validate checks the field values on UpdateWorkspaceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateWorkspaceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateWorkspaceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateWorkspaceRequestMultiError, or nil if none found.
func (m *UpdateWorkspaceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateWorkspaceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetCoordinates()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateWorkspaceRequestValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateWorkspaceRequestValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCoordinates()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateWorkspaceRequestValidationError{
				field:  "Coordinates",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for FullAddress

	// no validation rules for Type

	// no validation rules for Capacity

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateWorkspaceRequestMultiError(errors)
	}

	return nil
}

// UpdateWorkspaceRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateWorkspaceRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateWorkspaceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateWorkspaceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateWorkspaceRequestMultiError) AllErrors() []error { return m }

// UpdateWorkspaceRequestValidationError is the validation error returned by
// UpdateWorkspaceRequest.Validate if the designated constraints aren't met.
type UpdateWorkspaceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateWorkspaceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateWorkspaceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateWorkspaceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateWorkspaceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateWorkspaceRequestValidationError) ErrorName() string {
	return "UpdateWorkspaceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateWorkspaceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateWorkspaceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateWorkspaceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateWorkspaceRequestValidationError{}

// Validate checks the field values on UpdateWorkspaceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateWorkspaceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateWorkspaceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateWorkspaceResponseMultiError, or nil if none found.
func (m *UpdateWorkspaceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateWorkspaceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateWorkspaceResponseMultiError(errors)
	}

	return nil
}

// UpdateWorkspaceResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateWorkspaceResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateWorkspaceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateWorkspaceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateWorkspaceResponseMultiError) AllErrors() []error { return m }

// UpdateWorkspaceResponseValidationError is the validation error returned by
// UpdateWorkspaceResponse.Validate if the designated constraints aren't met.
type UpdateWorkspaceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateWorkspaceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateWorkspaceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateWorkspaceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateWorkspaceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateWorkspaceResponseValidationError) ErrorName() string {
	return "UpdateWorkspaceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateWorkspaceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateWorkspaceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateWorkspaceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateWorkspaceResponseValidationError{}

// Validate checks the field values on DeleteWorkspaceByIdRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteWorkspaceByIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteWorkspaceByIdRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteWorkspaceByIdRequestMultiError, or nil if none found.
func (m *DeleteWorkspaceByIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteWorkspaceByIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteWorkspaceByIdRequestMultiError(errors)
	}

	return nil
}

// DeleteWorkspaceByIdRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteWorkspaceByIdRequest.ValidateAll() if
// the designated constraints aren't met.
type DeleteWorkspaceByIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteWorkspaceByIdRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteWorkspaceByIdRequestMultiError) AllErrors() []error { return m }

// DeleteWorkspaceByIdRequestValidationError is the validation error returned
// by DeleteWorkspaceByIdRequest.Validate if the designated constraints aren't met.
type DeleteWorkspaceByIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteWorkspaceByIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteWorkspaceByIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteWorkspaceByIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteWorkspaceByIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteWorkspaceByIdRequestValidationError) ErrorName() string {
	return "DeleteWorkspaceByIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteWorkspaceByIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteWorkspaceByIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteWorkspaceByIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteWorkspaceByIdRequestValidationError{}

// Validate checks the field values on DeleteWorkspaceByIdResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteWorkspaceByIdResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteWorkspaceByIdResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteWorkspaceByIdResponseMultiError, or nil if none found.
func (m *DeleteWorkspaceByIdResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteWorkspaceByIdResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteWorkspaceByIdResponseMultiError(errors)
	}

	return nil
}

// DeleteWorkspaceByIdResponseMultiError is an error wrapping multiple
// validation errors returned by DeleteWorkspaceByIdResponse.ValidateAll() if
// the designated constraints aren't met.
type DeleteWorkspaceByIdResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteWorkspaceByIdResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteWorkspaceByIdResponseMultiError) AllErrors() []error { return m }

// DeleteWorkspaceByIdResponseValidationError is the validation error returned
// by DeleteWorkspaceByIdResponse.Validate if the designated constraints
// aren't met.
type DeleteWorkspaceByIdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteWorkspaceByIdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteWorkspaceByIdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteWorkspaceByIdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteWorkspaceByIdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteWorkspaceByIdResponseValidationError) ErrorName() string {
	return "DeleteWorkspaceByIdResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteWorkspaceByIdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteWorkspaceByIdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteWorkspaceByIdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteWorkspaceByIdResponseValidationError{}

// Validate checks the field values on ListWorkspacesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWorkspacesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWorkspacesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWorkspacesRequestMultiError, or nil if none found.
func (m *ListWorkspacesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWorkspacesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWorkspacesRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWorkspacesRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWorkspacesRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Filter != nil {

		if all {
			switch v := interface{}(m.GetFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListWorkspacesRequestValidationError{
						field:  "Filter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListWorkspacesRequestValidationError{
						field:  "Filter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListWorkspacesRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListWorkspacesRequestMultiError(errors)
	}

	return nil
}

// ListWorkspacesRequestMultiError is an error wrapping multiple validation
// errors returned by ListWorkspacesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListWorkspacesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWorkspacesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWorkspacesRequestMultiError) AllErrors() []error { return m }

// ListWorkspacesRequestValidationError is the validation error returned by
// ListWorkspacesRequest.Validate if the designated constraints aren't met.
type ListWorkspacesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWorkspacesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWorkspacesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWorkspacesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWorkspacesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWorkspacesRequestValidationError) ErrorName() string {
	return "ListWorkspacesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListWorkspacesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWorkspacesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWorkspacesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWorkspacesRequestValidationError{}

// Validate checks the field values on ListWorkspacesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWorkspacesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWorkspacesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWorkspacesResponseMultiError, or nil if none found.
func (m *ListWorkspacesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWorkspacesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetWorkspaces() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListWorkspacesResponseValidationError{
						field:  fmt.Sprintf("Workspaces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListWorkspacesResponseValidationError{
						field:  fmt.Sprintf("Workspaces[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListWorkspacesResponseValidationError{
					field:  fmt.Sprintf("Workspaces[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return ListWorkspacesResponseMultiError(errors)
	}

	return nil
}

// ListWorkspacesResponseMultiError is an error wrapping multiple validation
// errors returned by ListWorkspacesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListWorkspacesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWorkspacesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWorkspacesResponseMultiError) AllErrors() []error { return m }

// ListWorkspacesResponseValidationError is the validation error returned by
// ListWorkspacesResponse.Validate if the designated constraints aren't met.
type ListWorkspacesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWorkspacesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWorkspacesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWorkspacesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWorkspacesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWorkspacesResponseValidationError) ErrorName() string {
	return "ListWorkspacesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListWorkspacesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWorkspacesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWorkspacesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWorkspacesResponseValidationError{}

// Validate checks the field values on GetWorkspaceByIdResponse_Workspace with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetWorkspaceByIdResponse_Workspace) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWorkspaceByIdResponse_Workspace
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetWorkspaceByIdResponse_WorkspaceMultiError, or nil if none found.
func (m *GetWorkspaceByIdResponse_Workspace) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWorkspaceByIdResponse_Workspace) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetCoordinates()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponse_WorkspaceValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponse_WorkspaceValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCoordinates()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetWorkspaceByIdResponse_WorkspaceValidationError{
				field:  "Coordinates",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for FullAddress

	// no validation rules for Type

	// no validation rules for Status

	// no validation rules for Capacity

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponse_WorkspaceValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponse_WorkspaceValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetWorkspaceByIdResponse_WorkspaceValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponse_WorkspaceValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetWorkspaceByIdResponse_WorkspaceValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetWorkspaceByIdResponse_WorkspaceValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetWorkspaceByIdResponse_WorkspaceMultiError(errors)
	}

	return nil
}

// GetWorkspaceByIdResponse_WorkspaceMultiError is an error wrapping multiple
// validation errors returned by
// GetWorkspaceByIdResponse_Workspace.ValidateAll() if the designated
// constraints aren't met.
type GetWorkspaceByIdResponse_WorkspaceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWorkspaceByIdResponse_WorkspaceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWorkspaceByIdResponse_WorkspaceMultiError) AllErrors() []error { return m }

// GetWorkspaceByIdResponse_WorkspaceValidationError is the validation error
// returned by GetWorkspaceByIdResponse_Workspace.Validate if the designated
// constraints aren't met.
type GetWorkspaceByIdResponse_WorkspaceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWorkspaceByIdResponse_WorkspaceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWorkspaceByIdResponse_WorkspaceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWorkspaceByIdResponse_WorkspaceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWorkspaceByIdResponse_WorkspaceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWorkspaceByIdResponse_WorkspaceValidationError) ErrorName() string {
	return "GetWorkspaceByIdResponse_WorkspaceValidationError"
}

// Error satisfies the builtin error interface
func (e GetWorkspaceByIdResponse_WorkspaceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWorkspaceByIdResponse_Workspace.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWorkspaceByIdResponse_WorkspaceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWorkspaceByIdResponse_WorkspaceValidationError{}

// Validate checks the field values on ListWorkspacesRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWorkspacesRequest_Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWorkspacesRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWorkspacesRequest_FilterMultiError, or nil if none found.
func (m *ListWorkspacesRequest_Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWorkspacesRequest_Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.CapacityGte != nil {
		// no validation rules for CapacityGte
	}

	if m.FullAddress != nil {
		// no validation rules for FullAddress
	}

	if len(errors) > 0 {
		return ListWorkspacesRequest_FilterMultiError(errors)
	}

	return nil
}

// ListWorkspacesRequest_FilterMultiError is an error wrapping multiple
// validation errors returned by ListWorkspacesRequest_Filter.ValidateAll() if
// the designated constraints aren't met.
type ListWorkspacesRequest_FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWorkspacesRequest_FilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWorkspacesRequest_FilterMultiError) AllErrors() []error { return m }

// ListWorkspacesRequest_FilterValidationError is the validation error returned
// by ListWorkspacesRequest_Filter.Validate if the designated constraints
// aren't met.
type ListWorkspacesRequest_FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWorkspacesRequest_FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWorkspacesRequest_FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWorkspacesRequest_FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWorkspacesRequest_FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWorkspacesRequest_FilterValidationError) ErrorName() string {
	return "ListWorkspacesRequest_FilterValidationError"
}

// Error satisfies the builtin error interface
func (e ListWorkspacesRequest_FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWorkspacesRequest_Filter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWorkspacesRequest_FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWorkspacesRequest_FilterValidationError{}

// Validate checks the field values on ListWorkspacesRequest_Page with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWorkspacesRequest_Page) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWorkspacesRequest_Page with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWorkspacesRequest_PageMultiError, or nil if none found.
func (m *ListWorkspacesRequest_Page) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWorkspacesRequest_Page) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListWorkspacesRequest_PageMultiError(errors)
	}

	return nil
}

// ListWorkspacesRequest_PageMultiError is an error wrapping multiple
// validation errors returned by ListWorkspacesRequest_Page.ValidateAll() if
// the designated constraints aren't met.
type ListWorkspacesRequest_PageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWorkspacesRequest_PageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWorkspacesRequest_PageMultiError) AllErrors() []error { return m }

// ListWorkspacesRequest_PageValidationError is the validation error returned
// by ListWorkspacesRequest_Page.Validate if the designated constraints aren't met.
type ListWorkspacesRequest_PageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWorkspacesRequest_PageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWorkspacesRequest_PageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWorkspacesRequest_PageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWorkspacesRequest_PageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWorkspacesRequest_PageValidationError) ErrorName() string {
	return "ListWorkspacesRequest_PageValidationError"
}

// Error satisfies the builtin error interface
func (e ListWorkspacesRequest_PageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWorkspacesRequest_Page.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWorkspacesRequest_PageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWorkspacesRequest_PageValidationError{}

// Validate checks the field values on ListWorkspacesResponse_Workspace with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListWorkspacesResponse_Workspace) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWorkspacesResponse_Workspace with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListWorkspacesResponse_WorkspaceMultiError, or nil if none found.
func (m *ListWorkspacesResponse_Workspace) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWorkspacesResponse_Workspace) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetCoordinates()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWorkspacesResponse_WorkspaceValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWorkspacesResponse_WorkspaceValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCoordinates()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWorkspacesResponse_WorkspaceValidationError{
				field:  "Coordinates",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for FullAddress

	// no validation rules for Type

	// no validation rules for Capacity

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWorkspacesResponse_WorkspaceValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWorkspacesResponse_WorkspaceValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWorkspacesResponse_WorkspaceValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWorkspacesResponse_WorkspaceValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWorkspacesResponse_WorkspaceValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWorkspacesResponse_WorkspaceValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if len(errors) > 0 {
		return ListWorkspacesResponse_WorkspaceMultiError(errors)
	}

	return nil
}

// ListWorkspacesResponse_WorkspaceMultiError is an error wrapping multiple
// validation errors returned by
// ListWorkspacesResponse_Workspace.ValidateAll() if the designated
// constraints aren't met.
type ListWorkspacesResponse_WorkspaceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWorkspacesResponse_WorkspaceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWorkspacesResponse_WorkspaceMultiError) AllErrors() []error { return m }

// ListWorkspacesResponse_WorkspaceValidationError is the validation error
// returned by ListWorkspacesResponse_Workspace.Validate if the designated
// constraints aren't met.
type ListWorkspacesResponse_WorkspaceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWorkspacesResponse_WorkspaceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWorkspacesResponse_WorkspaceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWorkspacesResponse_WorkspaceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWorkspacesResponse_WorkspaceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWorkspacesResponse_WorkspaceValidationError) ErrorName() string {
	return "ListWorkspacesResponse_WorkspaceValidationError"
}

// Error satisfies the builtin error interface
func (e ListWorkspacesResponse_WorkspaceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWorkspacesResponse_Workspace.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWorkspacesResponse_WorkspaceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWorkspacesResponse_WorkspaceValidationError{}
