// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/booking/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Booking with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Booking) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Booking with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BookingMultiError, or nil if none found.
func (m *Booking) ValidateAll() error {
	return m.validate(true)
}

func (m *Booking) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for WorkspaceId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetStartAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingValidationError{
				field:  "StartAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingValidationError{
				field:  "EndAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BookingMultiError(errors)
	}

	return nil
}

// BookingMultiError is an error wrapping multiple validation errors returned
// by Booking.ValidateAll() if the designated constraints aren't met.
type BookingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookingMultiError) AllErrors() []error { return m }

// BookingValidationError is the validation error returned by Booking.Validate
// if the designated constraints aren't met.
type BookingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookingValidationError) ErrorName() string { return "BookingValidationError" }

// Error satisfies the builtin error interface
func (e BookingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBooking.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookingValidationError{}

// Validate checks the field values on Page with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Page) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Page with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PageMultiError, or nil if none found.
func (m *Page) ValidateAll() error {
	return m.validate(true)
}

func (m *Page) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return PageMultiError(errors)
	}

	return nil
}

// PageMultiError is an error wrapping multiple validation errors returned by
// Page.ValidateAll() if the designated constraints aren't met.
type PageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageMultiError) AllErrors() []error { return m }

// PageValidationError is the validation error returned by Page.Validate if the
// designated constraints aren't met.
type PageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageValidationError) ErrorName() string { return "PageValidationError" }

// Error satisfies the builtin error interface
func (e PageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageValidationError{}

// Validate checks the field values on GetBookingByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBookingByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBookingByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBookingByIDRequestMultiError, or nil if none found.
func (m *GetBookingByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBookingByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetBookingByIDRequestMultiError(errors)
	}

	return nil
}

// GetBookingByIDRequestMultiError is an error wrapping multiple validation
// errors returned by GetBookingByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetBookingByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBookingByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBookingByIDRequestMultiError) AllErrors() []error { return m }

// GetBookingByIDRequestValidationError is the validation error returned by
// GetBookingByIDRequest.Validate if the designated constraints aren't met.
type GetBookingByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBookingByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBookingByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBookingByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBookingByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBookingByIDRequestValidationError) ErrorName() string {
	return "GetBookingByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBookingByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBookingByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBookingByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBookingByIDRequestValidationError{}

// Validate checks the field values on GetBookingByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBookingByIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBookingByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBookingByIDResponseMultiError, or nil if none found.
func (m *GetBookingByIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBookingByIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBooking()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetBookingByIDResponseValidationError{
					field:  "Booking",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetBookingByIDResponseValidationError{
					field:  "Booking",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBooking()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBookingByIDResponseValidationError{
				field:  "Booking",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetBookingByIDResponseMultiError(errors)
	}

	return nil
}

// GetBookingByIDResponseMultiError is an error wrapping multiple validation
// errors returned by GetBookingByIDResponse.ValidateAll() if the designated
// constraints aren't met.
type GetBookingByIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBookingByIDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBookingByIDResponseMultiError) AllErrors() []error { return m }

// GetBookingByIDResponseValidationError is the validation error returned by
// GetBookingByIDResponse.Validate if the designated constraints aren't met.
type GetBookingByIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBookingByIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBookingByIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBookingByIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBookingByIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBookingByIDResponseValidationError) ErrorName() string {
	return "GetBookingByIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBookingByIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBookingByIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBookingByIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBookingByIDResponseValidationError{}

// Validate checks the field values on CreateBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBookingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBookingRequestMultiError, or nil if none found.
func (m *CreateBookingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBookingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkspaceId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetStartAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "StartAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBookingRequestValidationError{
				field:  "StartAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "EndAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBookingRequestValidationError{
				field:  "EndAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateBookingRequestMultiError(errors)
	}

	return nil
}

// CreateBookingRequestMultiError is an error wrapping multiple validation
// errors returned by CreateBookingRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateBookingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBookingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBookingRequestMultiError) AllErrors() []error { return m }

// CreateBookingRequestValidationError is the validation error returned by
// CreateBookingRequest.Validate if the designated constraints aren't met.
type CreateBookingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBookingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBookingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBookingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBookingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBookingRequestValidationError) ErrorName() string {
	return "CreateBookingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBookingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBookingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBookingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBookingRequestValidationError{}

// Validate checks the field values on CreateBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBookingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBookingResponseMultiError, or nil if none found.
func (m *CreateBookingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBookingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BookingId

	if len(errors) > 0 {
		return CreateBookingResponseMultiError(errors)
	}

	return nil
}

// CreateBookingResponseMultiError is an error wrapping multiple validation
// errors returned by CreateBookingResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateBookingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBookingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBookingResponseMultiError) AllErrors() []error { return m }

// CreateBookingResponseValidationError is the validation error returned by
// CreateBookingResponse.Validate if the designated constraints aren't met.
type CreateBookingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBookingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBookingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBookingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBookingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBookingResponseValidationError) ErrorName() string {
	return "CreateBookingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBookingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBookingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBookingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBookingResponseValidationError{}

// Validate checks the field values on CancelBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelBookingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelBookingRequestMultiError, or nil if none found.
func (m *CancelBookingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelBookingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CancelBookingRequestMultiError(errors)
	}

	return nil
}

// CancelBookingRequestMultiError is an error wrapping multiple validation
// errors returned by CancelBookingRequest.ValidateAll() if the designated
// constraints aren't met.
type CancelBookingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelBookingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelBookingRequestMultiError) AllErrors() []error { return m }

// CancelBookingRequestValidationError is the validation error returned by
// CancelBookingRequest.Validate if the designated constraints aren't met.
type CancelBookingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelBookingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelBookingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelBookingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelBookingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelBookingRequestValidationError) ErrorName() string {
	return "CancelBookingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelBookingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelBookingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelBookingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelBookingRequestValidationError{}

// Validate checks the field values on CancelBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelBookingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelBookingResponseMultiError, or nil if none found.
func (m *CancelBookingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelBookingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CancelBookingResponseMultiError(errors)
	}

	return nil
}

// CancelBookingResponseMultiError is an error wrapping multiple validation
// errors returned by CancelBookingResponse.ValidateAll() if the designated
// constraints aren't met.
type CancelBookingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelBookingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelBookingResponseMultiError) AllErrors() []error { return m }

// CancelBookingResponseValidationError is the validation error returned by
// CancelBookingResponse.Validate if the designated constraints aren't met.
type CancelBookingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelBookingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelBookingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelBookingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelBookingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelBookingResponseValidationError) ErrorName() string {
	return "CancelBookingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CancelBookingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelBookingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelBookingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelBookingResponseValidationError{}

// Validate checks the field values on CompleteBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CompleteBookingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CompleteBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CompleteBookingRequestMultiError, or nil if none found.
func (m *CompleteBookingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CompleteBookingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CompleteBookingRequestMultiError(errors)
	}

	return nil
}

// CompleteBookingRequestMultiError is an error wrapping multiple validation
// errors returned by CompleteBookingRequest.ValidateAll() if the designated
// constraints aren't met.
type CompleteBookingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CompleteBookingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CompleteBookingRequestMultiError) AllErrors() []error { return m }

// CompleteBookingRequestValidationError is the validation error returned by
// CompleteBookingRequest.Validate if the designated constraints aren't met.
type CompleteBookingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CompleteBookingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CompleteBookingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CompleteBookingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CompleteBookingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CompleteBookingRequestValidationError) ErrorName() string {
	return "CompleteBookingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CompleteBookingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCompleteBookingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CompleteBookingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CompleteBookingRequestValidationError{}

// Validate checks the field values on CompleteBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CompleteBookingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CompleteBookingResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CompleteBookingResponseMultiError, or nil if none found.
func (m *CompleteBookingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CompleteBookingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CompleteBookingResponseMultiError(errors)
	}

	return nil
}

// CompleteBookingResponseMultiError is an error wrapping multiple validation
// errors returned by CompleteBookingResponse.ValidateAll() if the designated
// constraints aren't met.
type CompleteBookingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CompleteBookingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CompleteBookingResponseMultiError) AllErrors() []error { return m }

// CompleteBookingResponseValidationError is the validation error returned by
// CompleteBookingResponse.Validate if the designated constraints aren't met.
type CompleteBookingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CompleteBookingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CompleteBookingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CompleteBookingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CompleteBookingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CompleteBookingResponseValidationError) ErrorName() string {
	return "CompleteBookingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CompleteBookingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCompleteBookingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CompleteBookingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CompleteBookingResponseValidationError{}

// Validate checks the field values on ListBookingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListBookingsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBookingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBookingsRequestMultiError, or nil if none found.
func (m *ListBookingsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBookingsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListBookingsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListBookingsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListBookingsRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Filter != nil {

		if all {
			switch v := interface{}(m.GetFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsRequestValidationError{
						field:  "Filter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsRequestValidationError{
						field:  "Filter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListBookingsRequestMultiError(errors)
	}

	return nil
}

// ListBookingsRequestMultiError is an error wrapping multiple validation
// errors returned by ListBookingsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListBookingsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBookingsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBookingsRequestMultiError) AllErrors() []error { return m }

// ListBookingsRequestValidationError is the validation error returned by
// ListBookingsRequest.Validate if the designated constraints aren't met.
type ListBookingsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBookingsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBookingsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBookingsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBookingsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBookingsRequestValidationError) ErrorName() string {
	return "ListBookingsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListBookingsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBookingsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBookingsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBookingsRequestValidationError{}

// Validate checks the field values on ListBookingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListBookingsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBookingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBookingsResponseMultiError, or nil if none found.
func (m *ListBookingsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBookingsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBookings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsResponseValidationError{
						field:  fmt.Sprintf("Bookings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsResponseValidationError{
						field:  fmt.Sprintf("Bookings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsResponseValidationError{
					field:  fmt.Sprintf("Bookings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return ListBookingsResponseMultiError(errors)
	}

	return nil
}

// ListBookingsResponseMultiError is an error wrapping multiple validation
// errors returned by ListBookingsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListBookingsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBookingsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBookingsResponseMultiError) AllErrors() []error { return m }

// ListBookingsResponseValidationError is the validation error returned by
// ListBookingsResponse.Validate if the designated constraints aren't met.
type ListBookingsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBookingsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBookingsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBookingsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBookingsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBookingsResponseValidationError) ErrorName() string {
	return "ListBookingsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListBookingsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBookingsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBookingsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBookingsResponseValidationError{}

// Validate checks the field values on ListBookingsRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListBookingsRequest_Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBookingsRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBookingsRequest_FilterMultiError, or nil if none found.
func (m *ListBookingsRequest_Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBookingsRequest_Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.UserId != nil {
		// no validation rules for UserId
	}

	if m.WorkspaceId != nil {
		// no validation rules for WorkspaceId
	}

	if m.DateFrom != nil {

		if all {
			switch v := interface{}(m.GetDateFrom()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "DateFrom",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "DateFrom",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDateFrom()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsRequest_FilterValidationError{
					field:  "DateFrom",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DateTo != nil {

		if all {
			switch v := interface{}(m.GetDateTo()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "DateTo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "DateTo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDateTo()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsRequest_FilterValidationError{
					field:  "DateTo",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListBookingsRequest_FilterMultiError(errors)
	}

	return nil
}

// ListBookingsRequest_FilterMultiError is an error wrapping multiple
// validation errors returned by ListBookingsRequest_Filter.ValidateAll() if
// the designated constraints aren't met.
type ListBookingsRequest_FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBookingsRequest_FilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBookingsRequest_FilterMultiError) AllErrors() []error { return m }

// ListBookingsRequest_FilterValidationError is the validation error returned
// by ListBookingsRequest_Filter.Validate if the designated constraints aren't met.
type ListBookingsRequest_FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBookingsRequest_FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBookingsRequest_FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBookingsRequest_FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBookingsRequest_FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBookingsRequest_FilterValidationError) ErrorName() string {
	return "ListBookingsRequest_FilterValidationError"
}

// Error satisfies the builtin error interface
func (e ListBookingsRequest_FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBookingsRequest_Filter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBookingsRequest_FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBookingsRequest_FilterValidationError{}
